In [2]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [3]:
iris = load_iris() 

In [4]:
l_score = cross_val_score(LogisticRegression(), iris.data, iris.target, cv=3)
l_score

C:\Users\Lenovo\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.98, 0.96, 0.98])

In [5]:
np.average(l_score)

np.float64(0.9733333333333333)

In [10]:
d_scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target, cv=3)
d_scores


array([0.98, 0.92, 1.  ])

In [12]:
np.average(d_scores)

np.float64(0.9666666666666667)

In [9]:
s_scores = cross_val_score(SVC(), iris.data, iris.target, cv=3)
s_scores

array([0.96, 0.98, 0.94])

In [13]:
np.average(s_scores)

np.float64(0.96)

In [8]:
r_scores = cross_val_score(RandomForestClassifier(n_estimators=40), iris.data, iris.target, cv=3)
r_scores

array([0.98, 0.92, 0.96])

In [14]:
np.average(r_scores)

np.float64(0.9533333333333333)

### **`So logistic Regression performs the best`**